import { Brand } from "./brand.js";
import { Channel } from "./channel.js";
import { CommercialType } from "./commercialType.js";
import { Commercial } from "./commercial.js";
import { Order } from "./order.js";
import { PlacementType } from "./placementType.js";
import { TargetAudience } from "./targetAudience.js";
import { VipDate } from "./vipDate.js";
import { Discount } from "./discount.js";

export interface Mediaplan {
    id?: number;
    order_id: number;
    brand_id: number;
    channel_id: number;
    placement_type_id: number;
    commercial_type_id: number;
    target_audience_id: number;
    distribution_type?: number;
    name: string;
    taxes?: boolean;
    is_closed?: boolean;
    is_automatic?: boolean;
    disallow_ejection?: boolean;
    is_one_commercial_in_block?: boolean;
    is_fixed_price_blocks_allowed?: boolean;
    estimated_budget?: number;
    plan_budget?: number;
    fact_budget?: number;
    plan_fact_budget?: number;
    commitment_budget?: number;
    pure_mp_plan_wgrp?: number;
    pure_commitment_wgrp?: number;
    pure_mp_fact_wgrp?: number;
    pure_mp_plan_fact_wgrp?: number;
    pure_mp_plan_fact_wgrp_prime?: number;
    pure_mp_plan_fact_wgrp_off_prime?: number;
    mp_plan_wgrp?: number;
    commitment_wgrp?: number;
    mp_fact_wgrp?: number;
    mp_plan_fact_wgrp?: number;
    mp_plan_fact_wgrp_prime?: number;
    mp_plan_fact_wgrp_off_prime?: number;
    discount_coefficient?: number;
    placement_type_discount_coefficient?: number;
    basic_cpp_prime_cost?: number;
    basic_cpp_off_prime_cost?: number;
    spots_count?: number;
    spots_duration?: number;
    is_budget_fixed?: boolean;
    date_from: string;
    date_to: string;
    premium_position_discounts?: {
        "1F"?: number;
        "2F"?: number;
        "3F"?: number;
        "3L"?: number;
        "2L"?: number;
        "1L"?: number;
    } | null;
    created_at?: string;
    updated_at?: string;
    is_calculating?: number;
    order?: Order;
    brand?: Brand | null;
    channel?: Channel;
    placement_type?: PlacementType;
    commercial_type?: CommercialType;
    target_audience?: TargetAudience;
    commercials?: Commercial[];
    vip_dates?: VipDate[];
    discounts?: Discount[];
    is_vip?: boolean;
}
